Repository UN-OCHA/hpc-repo-tools, pull requests merged in 2025-03, with the labels that each got.

#80 Convert `hpc-repo-tools` to pure ESM
  .commitlintrc.base.json
  README.md
  commitlint.config.base.js
  eslint.config.base.js
  package.json
  prettier.config.base.js
Labels: ready for review

#81 Check formatting in CI
  .github/workflows/ci.yml
  commitlint.config.base.js
  package.json
Labels: ready for merge

#82 Update typescript and typescript eslint
  package-lock.json
  package.json
Labels: deployment, ready for review

#84 Add shell script formatting support
  .github/CODEOWNERS
  .gitignore
  .npmignore
  .prettierignore
  package-lock.json
  package.json
  prettier.config.base.js
Labels: ready for merge

#83 Unicorn import change
  eslint.config.base.js
Labels: ready for merge

#85 Update dependencies
  package-lock.json
  package.json
Labels: ready for merge, deployment

#86 Remove XML plugin
  package-lock.json
  package.json
  prettier.config.base.js
Labels: ready for merge
