Repository UN-OCHA/hpc-repo-tools, pull requests merged in 2025-02, with the labels that each got.

#68 Update dependencies
  package-lock.json
  package.json
Labels: ready for merge, dependencies

#69 Fix linting config and update `eslint` to `v9.21.0`
  eslint.config.base.js
  package-lock.json
  package.json
Labels: dependencies, ready for review

#70 Remove `@typescript-eslint/no-var-requires`
  eslint.config.base.js
Labels: ready for review

#71 🔖 Bump version to `v5.7.0`
  package-lock.json
  package.json
Labels: deployment

#72 Disable some `unicorn` rules
  eslint.config.base.js
Labels: ready for review

#73 🔖 Bump version to `v5.7.1`
  package-lock.json
  package.json
Labels: deployment
